import Head from "next/head";

import SideBar from "@/components/SideBar/SideBar";
import Header from "@/components/Header/Header";
import { FC, ReactNode } from "react";

type MainLayoutProps = {
  children: ReactNode;
};

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  return (
    <div className="min-h-screen bg-base-100">
      <Head>
        <title>Tech-Test | Felipe Róman</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-row">
        <SideBar />
        <div className="w-full">
          <Header />
          <div className="bg-base-100">{children}</div>
        </div>
      </div>
    </div>
  );
};

export default MainLayout;
